add system fiability integration skip tool process in message welcome…
Scriptor-Group/devana-react pull request #3
Opened 2024-07-09 11:32 UTC by ThomasDev28

… message

add icon tools ui && fix fiability on message

delete env

2024-07-09 11:39 UTC, xonlly requested changes

2024-07-09 11:39 UTC, xonlly commented on src/Components/Conversation.module.css
> +  min-width: 600px;
300px

2024-07-09 11:39 UTC, xonlly commented on package.json
> +    "": "yarn build",
prepublish

2024-07-09 11:39 UTC, xonlly commented on src/Components/Conversation.tsx
> +          console.log("message.trim().length > 0 && !displayTools", message);
```suggestion
```

2024-07-09 11:39 UTC, xonlly commented on src/Components/Conversation.tsx
> +    console.log("handleResetConversation");
```suggestion
```

2024-07-09 11:39 UTC, xonlly commented on src/Components/Conversation.tsx
> +                          {fiability_key === "BAD" ? (
Why not use, const for that ?
```suggestion
                          {fiability_key === FiabilityEnum.BAD ? (
```

2024-07-09 11:39 UTC, xonlly commented on assets/google.png
Please resize this picture to 28px by 28

2024-07-09 11:41 UTC, xonlly commented
Please update Markdown with new props

2024-07-09 12:24 UTC, Slashgear requested changes

2024-07-09 12:24 UTC, Slashgear commented on src/config.ts
> -export const API_URL = `https://api.devana.ai/`;
Issue:
Are we sure we want to use the http version ?
We will need to use https

2024-07-09 17:26 UTC, Slashgear approved these changes

2024-07-11 10:58 UTC, xonlly approved these changes
🌈

2024-07-11 11:01 UTC, merged